# Generated by Django 4.0.3 on 2022-03-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono_Cliente',
            field=models.CharField(max_length=255),
        ),
    ]
